# Generated by Django 5.2.6 on 2026-09-24 15:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_shareholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
