# Generated by Django 5.2.6 on 2026-09-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_shareholder_contribution_and_more'),
        ('billing', '0005_alter_shareholder_percentage'),
    ]

    operations = [
    ]
