# Generated by Django 5.2.6 on 2026-09-25 07:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_merge_20260925_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
    ]
