# Generated by Django 5.2.6 on 2026-09-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_shareholder_percentage'),
        ('billing', '0007_withdrawalrequest'),
    ]

    operations = [
    ]
