# Generated by Django 5.2.6 on 2026-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_shareholder_payment_details_shareincreaserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='payment_account_name',
            field=models.CharField(blank=True, help_text='Default payout account name, auto-filled onto every new withdrawal request.', max_length=150),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='payment_phone',
            field=models.CharField(blank=True, help_text='Default payout phone number, auto-filled onto every new withdrawal request.', max_length=20),
        ),
    ]
