# Generated by Django 5.2.6 on 2026-10-02 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_shareholder_payment_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('subscription_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('distributable_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paid_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_earningsperiod',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareholderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Unpaid'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='billing.earningsperiod')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='billing.shareholder')),
            ],
            options={
                'db_table': 'billing_shareholderpayout',
                'ordering': ['-percentage'],
                'constraints': [models.UniqueConstraint(fields=('period', 'shareholder'), name='uniq_payout_per_period_shareholder')],
            },
        ),
    ]
