# Generated by Django 5.2.6 on 2026-09-04 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_batches', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_batches', to='packages.internetpackage')),
            ],
            options={
                'db_table': 'vouchers_voucherbatch',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('DEACTIVATED', 'Deactivated')], default='UNUSED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='customers.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='packages.internetpackage')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.voucherbatch')),
            ],
            options={
                'db_table': 'vouchers_voucher',
            },
        ),
    ]
