# Generated by Django 5.2.6 on 2026-09-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
