# Generated by Django 5.2.6 on 2026-09-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('download_speed_kbps', models.PositiveIntegerField(help_text='Download speed in kbps')),
                ('upload_speed_kbps', models.PositiveIntegerField(help_text='Upload speed in kbps')),
                ('session_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'packages_packageprofile',
            },
        ),
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Numeric duration, combined with duration_unit')),
                ('duration_unit', models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days')], default='HOURS', max_length=10)),
                ('download_speed_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_speed_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('data_allowance_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('unlimited_data', models.BooleanField(default=True)),
                ('device_limit', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mikrotik_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='mikrotik.mikrotikprofile')),
                ('package_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packageprofile')),
            ],
            options={
                'db_table': 'packages_internetpackage',
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
