# Generated by Django 5.2.6 on 2026-09-04 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='NABISWA WIFI', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('support_info', models.TextField(blank=True)),
                ('wifi_name', models.CharField(blank=True, max_length=100)),
                ('portal_message', models.CharField(blank=True, default='Choose a package to connect', max_length=255)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('default_device_limit', models.PositiveSmallIntegerField(default=1)),
                ('renewal_behavior', models.CharField(choices=[('EXTEND', 'Extend current entitlement'), ('QUEUE', 'Queue after current entitlement'), ('IMMEDIATE', 'Start immediately, replacing current')], default='EXTEND', help_text='Default behavior in Section 12 when a customer buys a package while one is still active.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'core_systemsettings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment successful'), ('PAYMENT_FAILED', 'Payment failed'), ('PACKAGE_ACTIVATED', 'Package activated'), ('PACKAGE_EXPIRING', 'Package expiring'), ('PACKAGE_EXPIRED', 'Package expired'), ('ACCOUNT_SUSPENDED', 'Account suspended'), ('SYSTEM_ERROR', 'System error')], max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], default='IN_APP', max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx')],
            },
        ),
    ]
