# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_total_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False, help_text='Ticked once a staff member has reached out to this customer by phone.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedback',
                'db_table': 'core_customerfeedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
