# Generated by Django 5.2.6 on 2026-09-25 13:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='subscription_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('5500.00'), max_digits=12),
        ),
    ]
