# Generated by Django 5.2.6 on 2026-10-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_subscription_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_count', models.PositiveSmallIntegerField(default=0)),
                ('valid_on', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_time_adjustment_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_adjustment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_timeadjustmentrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
