# Generated by Django 5.2.6 on 2026-09-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(help_text='IP address or hostname', max_length=255)),
                ('api_port', models.PositiveIntegerField(default=8728)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=False, help_text='Use the encrypted API port (normally 8729)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('AUTH_FAILED', 'Authentication Failed'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error')], default='UNKNOWN', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mikrotik_router',
            },
        ),
        migrations.CreateModel(
            name='MikroTikProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(help_text='Exact profile name as configured on the router', max_length=100)),
                ('rate_limit', models.CharField(blank=True, help_text="e.g. '2M/5M'", max_length=50)),
                ('session_timeout', models.CharField(blank=True, help_text="e.g. '01:00:00'", max_length=20)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'db_table': 'mikrotik_profile',
                'constraints': [models.UniqueConstraint(fields=('router', 'profile_name'), name='unique_router_profile')],
            },
        ),
        migrations.CreateModel(
            name='InternetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mikrotik_username', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='customers.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='billing.subscription')),
                ('router', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'db_table': 'mikrotik_internetsession',
                'indexes': [models.Index(fields=['status'], name='mikrotik_in_status_f8f6a7_idx')],
            },
        ),
    ]
