# Generated by Django 5.2.6 on 2026-09-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('CREATE_USER', 'Create hotspot user'), ('DISCONNECT_USER', 'Disconnect user')], max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('result_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'db_table': 'mikrotik_job',
                'indexes': [models.Index(fields=['router', 'status'], name='mikrotik_jo_router__acc802_idx')],
            },
        ),
    ]
