# Generated by Django 5.2.6 on 2026-09-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_mac_address'),
        ('mikrotik', '0004_bypass_mac_job_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetsession',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='billing.payment'),
        ),
    ]
