# Generated by Django 5.2.6 on 2026-09-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0005_internetsession_payment'),
        ('vouchers', '0002_voucher_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetsession',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vouchers.voucher'),
        ),
    ]
